var rooms = [
    {
        'roomname':'entrance',
        'roomimage':'entrance',
        'rowcols' : [
            {
                'name':'upstairs',
                'destination':'georgewashingtonroom',
                'row':4,
                'col':5
            },
            {
                'name':'left',
                'destination':'',
                'row':7,
                'col':1
            },{
                'name':'right',
                'destination':'',
                'row':7,
                'col':9
            }
        ]
    },{
        'roomname':'georgewashingtonroom',
        'roomimage':'georgewashingtonroom',
        'rowcols' : [
            {
                'name':'return',
                'destination':'entrance',
                'rotation':180,
                'row':10,
                'col':5
            },{
                'name':'',
                'destination':'',
                'rotation':90,
                'row':5,
                'col':8
            },{
                'name':'',
                'destination':'',
                'rotation':90,
                'row':6,
                'col':10
            }
        ]
    }
];