var rooms = [
    {
        'roomname':'Entrance',
        'roomimage':'entrance',
        'rowcols' : [
            {
                'name':'upstairs',
                'destination':'GeorgeWashington',
                'row':4,
                'col':5
            },
            {
                'name':'left',
                'destination':'Hamilton',
                'row':7,
                'col':1
            },{
                'name':'right',
                'destination':'',
                'row':7,
                'col':9
            }
        ]
    },{
        'roomname':'GeorgeWashington',
        'roomimage':'georgewashington',
        'rowcols' : [
            {
                'name':'return',
                'destination':'Entrance',
                'rotation':180,
                'row':9,
                'col':5
            },{
                'name':'',
                'destination':'',
                'rotation':90,
                'row':5,
                'col':8
            },{
                'name':'',
                'destination':'',
                'rotation':90,
                'row':6,
                'col':10
            }
        ]
    },{
        'roomname':'Hamilton',
        'roomimage':'hamilton',
        'rowcols':[
            {
                'name':'',
                'destination':'Entrance',
                'rotation':180,
                'row':9,
                'col':5
            }
        ]
    }
];